services:
    PostalCodesDatabase:
        image: mariadb
        container_name: postal_codes_database

        ports:
            - 3306:3306

        environment: 
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        
        volumes:
            - ./Database/01_AlterDatabase.sql:/docker-entrypoint-initdb.d/01_AlterDatabase.sql
            - ./Database/02_CreateTable.sql:/docker-entrypoint-initdb.d/02_CreateTable.sql
            - DataPostalCodes:/var/lib/mysql:Z

    PipelineETL:
        build:
            context: ./Pipeline
            dockerfile: Dockerfile
        container_name: pipeline_etl
        image: pipeline-etl-postal-codes

        environment:
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_HOST: PostalCodesDatabase

        volumes:
            - ./Pipeline/CPdescargaxls.zip:/CPdescargaxls.zip

        depends_on:
            - PostalCodesDatabase

    AddressFinderWebInterface:
        build:
            context: ./AddressFinder
            dockerfile: Dockerfile
        container_name: address_finder_web
        image: address-finder-web-interface

        ports:
            - 8080:8080

        environment:
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_HOST: PostalCodesDatabase
            SECRET_KEY_FLASK: ${SECRET_KEY_FLASK}

        depends_on:
            - PostalCodesDatabase

volumes:
    DataPostalCodes: